import { Database } from 'bun:sqlite'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'
import { SCHEMA } from './schema'
// code-spider-ohm
import { debugLog } from '../utils/debug'

// code-spider-ohm
// The default DB lives repo-locally in .code-spider/. A committed database is
// a hazard: this repo once had its WAL committed mid-write, corrupting the
// index. When we own the directory, drop a .gitignore so the cache
// self-excludes (same pattern as .terraform). User files like config.yaml are
// not ignored. Never overwrite an existing .gitignore.
function ensureCacheGitignore(dbDir: string): void {
  if (basename(dbDir) !== '.code-spider') return
  const gitignorePath = join(dbDir, '.gitignore')
  if (existsSync(gitignorePath)) return
  try {
    writeFileSync(gitignorePath, '# Generated by code-spider — the index is a local cache, never commit it.\nindex.db*\n')
  } catch (err) {
    debugLog('db', `failed to write ${gitignorePath}`, err)
  }
}

function initializeSchema(db: Database): void {
  db.query('PRAGMA journal_mode=WAL;').run()
  for (const stmt of SCHEMA) {
    db.query(stmt).run()
  }
  migrateExistingTables(db)
}

// code-spider-0ok
// CREATE TABLE IF NOT EXISTS never alters an existing table, so column
// additions need explicit pragma-guarded ALTERs for databases created
// before the column existed. Same idempotent-on-every-open spirit as the
// schema loop above.
function migrateExistingTables(db: Database): void {
  const edgeCols = db.query('PRAGMA table_info(edges)').all() as Array<{ name: string }>
  if (!edgeCols.some(c => c.name === 'confidence')) {
    db.query('ALTER TABLE edges ADD COLUMN confidence REAL NOT NULL DEFAULT 1').run()
  }
}

export function openDb(dbPath: string): Database {
  mkdirSync(dirname(dbPath), { recursive: true })
  // code-spider-ohm
  ensureCacheGitignore(dirname(dbPath))
  const db = new Database(dbPath, { create: true })
  db.query('PRAGMA busy_timeout=5000;').run()
  db.query('PRAGMA foreign_keys=ON;').run()

  // code-spider-xbf
  // Always run the schema: every statement is IF NOT EXISTS, so this is
  // idempotent and cheap — and it lets additions (new tables, new indexes)
  // apply to existing databases. The old needsInitialization() gate only
  // checked tables, so index additions never reached older DBs.
  initializeSchema(db)

  return db
}
